HomeWork 2
AliakseiBychyk/nodejs-cdp-2018-abychyk pull request #1
Opened 2018-04-26 08:35 UTC by AliakseiBychyk

2018-05-04 08:19 UTC, EduardTrutsyk commented
в будущем все задания будут в одном и том же репозитории, для удобства эти модули лучше переместить в отдельную папку, например `modules`

2018-05-04 08:36 UTC, EduardTrutsyk requested changes

2018-05-04 08:36 UTC, EduardTrutsyk commented on dirwatcher.js
> +  watch = (path, delay) => {
было бы хорошо иметь метод `unwatch`

2018-05-04 08:36 UTC, EduardTrutsyk commented on dirwatcher.js
> +          this.emit('changed')
в задании сказано что событие должно называться `dirwatcher:changed`

2018-05-04 08:36 UTC, EduardTrutsyk commented on importer.js
> +    const read = (filePath) => {
каждый раз при вызове функции `import` , будет создаваться новая функция `read`, и это не очень хорошо, лучше вынести ее отдельно, т.к. она они не зависит от контекста

2018-05-04 08:36 UTC, EduardTrutsyk commented on importer.js
> +      emitter.on('changed', (err) => {
промис разрезолвится только один раз, а не на каждое событие, лучше сделать отдельны метод `addListener` что бы можно бло добавить несколько подписчиков, и все они слушали изменения, а метод `import` просто делал свою работу.

2018-05-04 08:52 UTC, AliakseiBychyk commented on dirwatcher.js
> +  watch = (path, delay) => {
did everything according to the task, but ok - will do that

2018-05-04 08:53 UTC, AliakseiBychyk commented on dirwatcher.js
> +          this.emit('changed')
ok, misunderstood

2018-05-04 08:56 UTC, AliakseiBychyk commented on importer.js
> +    const read = (filePath) => {
First placed this 'read' function as the class method, but later decide to make it local, but you're surely right

2018-05-04 08:58 UTC, AliakseiBychyk commented on importer.js
> +      emitter.on('changed', (err) => {
That's the part of my code I didn't like how it worked the most!

2018-05-04 11:12 UTC, AliakseiBychyk commented on dirwatcher.js
> +  watch = (path, delay) => {
done

2018-05-04 13:06 UTC, EduardTrutsyk requested changes

2018-05-04 13:06 UTC, EduardTrutsyk commented on importer.js
> +  read = (filePath) => {
у импортера не должно быть лишних паблик методов

2018-05-04 13:06 UTC, EduardTrutsyk commented on importer.js
> +  subscribeListenerForImport = (emitter, dir) => {
не нужно передавать `emitter`, я должен использовать модуль `Importer` как самостоятельный модуль, он должен знать про `emitter` а не я

2018-05-04 13:06 UTC, EduardTrutsyk commented on app.js
> +importer.subscribeListenerForImport(watcher, './data')
`DirWatcher` и `Importer` два отдельных модуля, только `Importer` внутри должен занть про `DirWatcher`. Либо при создании нового `importer` инжектить экземпляр `DirWatcher`. Почитай про `dependency injection`.
суть метода `subscribeListenerForImport` должа быть такой же, как `addEventListener` у любого DOM элемента.

2018-05-04 13:07 UTC, EduardTrutsyk commented on app.js
> +importer.subscribeListenerForImport(watcher, './data')
должна быть возможность добавить двух подписчиков, например они будут выводить в консоль данные каждый со своим префиксом.

2018-05-04 17:35 UTC, AliakseiBychyk commented on app.js
> +importer.subscribeListenerForImport(watcher, './data')
Done

2018-05-07 08:08 UTC, EduardTrutsyk approved these changes

2018-05-10 11:47 UTC, merged